### ISSUE TITLE
Shows white screen on iPhone SE 2

### ISSUE THREAD

**Issue by valeriyvan** [makeml-app/road_signs#2]
![IMG_0005](https://user-images.githubusercontent.com/1630974/85144534-91679f00-b24b-11ea-9faa-eda37aee7597.PNG)
No alert, no log message. Nothing.

**Comment by makeml-app** [comment]
Thanks for the pull request :)--Отправлено из мобильной Яндекс.Почты19.06.2020, 17:41, "Valeriy Van" <notifications@github.com>:

No alert, no log message. Nothing.

**Comment by valeriyvan** [comment]
Fixed with PR #3
